### PR TITLE
new features: dendogram as output and specifying number of desired clusters

### PR DESCRIPTION
**Pull request by zellerivo**
Dear Lorena Pantano, 

I am a frequent user of your package. Thank you very much for creating this nice tool ! 
I want to propose you my code here for adding two new features:

1. specifying the number of clusters for the trajectories
2. plotting the dendogram for the clusters

I have also changed the order of plots of the trajectories to be in numerical order instead of alphabetical.
I use this modified version of the package at our institute, I thought, maybe the features are helpful for others, as well.

Greetings from Munich, 

Ivo

### CODE REVIEW

**Comment by lpantano** [comment]
Hi @zellerivo , I totally missed this, so sorry. I will merge, test and deploy to BioC ASAP. Thanks

**Comment by zellerivo** [comment]
no worries @lpantano ! Thanks for taking the modifications into consideration

**Comment by lpantano** [comment]
Hi, let me look into it, sorry I have been traveling due to an emergency in my family. I will try to do it today.

**Comment by lpantano** [comment]
is in bioc 3.18 and getting changes into devel version as well. Thanks!

**Comment by lpantano** [comment]
if you give me your name and last name  I can add you as contributor to the package.

**Comment by zellerivo** [comment]
that is very kind. I am honored :) My full name is Ivo Zeller

**Pull request merged**
